### ISSUE TITLE
mod requests improvements

### ISSUE THREAD

**Issue by pishifat** [pishifat/qat#33]
- [ ] hightlight favs mappers ~~(adding a field to users model probably)~~
Should use the subscribed list from osu, no idea if it's available from users' endpoint, last time i checked it it wasn't, probably worth asking for it
- [ ] ~~1 month for previously accepted people~~ Giving even more credit to already stablished mappers isn't really aim, or something like that was the reason to not do it iirc
- [x] allow users to edit comments / "pls comment back if u got 2 bns already"
- [ ] dont allow to edit comments from bns (after some minutes), instead add new ones
- [ ] ~~sort by relevance (like a preview of points system) ? ?~~ Lets wait for a more stablished system i guess?

milans list

**Comment by iptq** [comment]
Got a couple more ideas for this one:

- Since cooldown is 2 months, make the queue 2 months long in total, flushing maps that are older than 2 months to keep map list fresh (where by "flush" i mean moving them to a "stale" state or something that can still be found by filtering specifically for stale but not show up by default, resubmitting that map in the queue just "unstales")
- For BNs looking at the queue, in addition to the regular filter-list, have a "summary" view like the Youtube homepage that shows newest requests being added _as well as_ oldest requests that are about to get flushed
- Allow all users to see all request details and overall stats for how many requests were submitted, reviewed, and accepted within the 2 month window
- Have a nightly cron job mark ranked maps as denied automatically / flush them from the queue

**Comment by milaneyia** [comment]
> Got a couple more ideas for this one:
> 
> * Since cooldown is 2 months, make the queue 2 months long in total, flushing maps that are older than 2 months to keep map list fresh (where by "flush" i mean moving them to a "stale" state or something that can still be found by filtering specifically for stale but not show up by default, resubmitting that map in the queue just "unstales")
> * Have a nightly cron job mark ranked maps as denied automatically / flush them from the queue

This could be doing using `updatedAt` from request model i think? Only loading requests till 2 months ago, unstaling would just update this date to today but requires something to only allow this every 2 months.

> * For BNs looking at the queue, in addition to the regular filter-list, have a "summary" view like the Youtube homepage that shows newest requests being added _as well as_ oldest requests that are about to get flushed

I wanted to have another kind of sorting, where the submission date, number of ranked maps, length and last time reviewed would have a collective value. So old submissions from people with no ranked maps, average length and never reviewed before would show at first.
Something along those lines would be better than having another list i think

> * Allow all users to see all request details and overall stats for how many requests were submitted, reviewed, and accepted within the 2 month window

Tbh this would discourage some people from posting. It's not that bad right now but can be better yeah

**Comment by pishifat** [comment]
im never getting around to this stuff sorry every1
